services:
  server:
    build: ./server
    ports:
      - 4000:4000
    command: yarn dev
    volumes:
      - ./server/src:/back/src
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/front/src
    command: yarn dev

